service: glm-data-stream

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: non-linux
  LIGHTNING_SNS: arn:aws:sns:${env:DEFAULT_REGION}:${env:AWS_ID}:${env:LIGHTNING_SNS}
  GOES16_SNS: arn:aws:sns:${env:DEFAULT_REGION}:${env:GOES16_ID}:${env:GOES16_SNS_TOPIC}

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:HeadObject
        - s3:ListBucket
      Resource: 
        - "arn:aws:s3:::${env:BUCKET_NAME}"
        - "arn:aws:s3:::${env:BUCKET_NAME}/*"

    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:HeadObject
        - s3:ListBucket
      Resource: 
        - "arn:aws:s3:::${env:GOES16_BUCKET}"
        - "arn:aws:s3:::${env:GOES16_BUCKET}/*"

    - Effect: Allow
      Action:
        - sns:Publish
      Resource: 
        - "${self:custom.LIGHTNING_SNS}"


functions:
  get-redemet-api:
    handler: handler.glm_data
    events:
      - sns: ${self:custom.GOES16_SNS}

resources:
 Resources:
   Bucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${env:BUCKET_NAME}
   Sns:
     Type: AWS::SNS::Topic
     Properties:
       TopicName: ${env:LIGHTNING_SNS}